### ISSUE TITLE
Improve “Open Browser and Connect” Button Functionality in v5

### ISSUE THREAD

**Issue by Totemancer** [tonkeeper/ios#47]
Since the release of version 5.0.1, a new “Open Browser and Connect” button has been introduced. Currently, this button opens the app URL in a browser without redirecting back to the original app, which is causing confusion among users. It would be more intuitive to offer two separate buttons:

1. Connect and Redirect
2. Open in Tonkeeper Browser

This change would provide clearer options and avoid the additional check required to connect.

**Details**:
	•	Relevant Code:
	•	[TonConnectConnectMapper.swift - Line 129](https://github.com/tonkeeper/ios/blob/main/LocalPackages/App/Sources/App/TonConnectModule/Modules/TonConnectConnect/TonConnectConnectMapper.swift#L129)
	•	[TonConnectConnectCoordinator.swift - Line 108](https://github.com/tonkeeper/ios/blob/main/LocalPackages/App/Sources/App/TonConnectModule/Flows/TonConnectConnectCoordinator.swift#L108)
	•	[TonConnectConnectViewModel.swift - Line 118](https://github.com/tonkeeper/ios/blob/6788bcb45597eae13cdf2d95e90354430a1b9498/LocalPackages/App/Sources/App/TonConnectModule/Modules/TonConnectConnect/TonConnectConnectViewModel.swift#L118)

The `connectAction` function does not currently call the `twaReturnUrl`, causing apps like Telegram Mini Apps and other web applications to be unable to redirect users back to the original app. 

**Suggested Improvements**:
	•	Implement two separate buttons: “Open in Browser” and “Connect and Redirect”
	•	Ensure connectAction calls the returnURL for proper redirection

**Comment by grishamsc** [comment]
Hello!
We've just release 5.0.2 version to AppStore with “Open Browser and Connect” feature rollback, redirect to original app fix and also missed`utm_source=tonkeeper` url appening.
Feel free to write here if this fix didn't help.
Appreciate your contribution 🙏

**Comment by Totemancer** [comment]
> Hello @Totemancer ! We've just release 5.0.2 version to AppStore with “Open Browser and Connect” feature rollback, redirect to original app fix and also missed`utm_source=tonkeeper` url appening. Feel free to write here if this fix didn't help. Appreciate your contribution 🙏

Amazing! Works perfectly now! Thank you for your work!

**Comment by marshmello37** [comment]
we test app in testnet but not redirect to app in directly. Is there any way to fix this problem?
